Traceback (most recent call last):
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Read in data
# Set up access to jetstream2
fs = fsspec.filesystem("s3", anon=True, client_kwargs=dict(endpoint_url=URL))
pattern = f"s3://{path}/kernels/"+kernel+f"/TOA*.nc"

# Grab the data
files = sorted(fs.glob(pattern))

# Open file and make it Xarray Dataset
kern = xr.open_dataset(fs.open(files[0]))

# Save path for later
path_out = files[0].split(kernel+"/",1)[1]
------------------


[31m---------------------------------------------------------------------------[39m
[31mValueError[39m                                Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[3][39m[32m, line 10[39m
[32m      7[39m files = [38;5;28msorted[39m(fs.glob(pattern))
[32m      9[39m [38;5;66;03m# Open file and make it Xarray Dataset[39;00m
[32m---> [39m[32m10[39m kern = [43mxr[49m[43m.[49m[43mopen_dataset[49m[43m([49m[43mfs[49m[43m.[49m[43mopen[49m[43m([49m[43mfiles[49m[43m[[49m[32;43m0[39;49m[43m][49m[43m)[49m[43m)[49m
[32m     12[39m [38;5;66;03m# Save path for later[39;00m
[32m     13[39m path_out = files[[32m0[39m].split(kernel+[33m"[39m[33m/[39m[33m"[39m,[32m1[39m)[[32m1[39m]

[36mFile [39m[32m~/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/xarray/backends/api.py:668[39m, in [36mopen_dataset[39m[34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)[39m
[32m    665[39m     kwargs.update(backend_kwargs)
[32m    667[39m [38;5;28;01mif[39;00m engine [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m--> [39m[32m668[39m     engine = [43mplugins[49m[43m.[49m[43mguess_engine[49m[43m([49m[43mfilename_or_obj[49m[43m)[49m
[32m    670[39m [38;5;28;01mif[39;00m from_array_kwargs [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m    671[39m     from_array_kwargs = {}

[36mFile [39m[32m~/micromamba/envs/feedback-cookbook-dev/lib/python3.11/site-packages/xarray/backends/plugins.py:194[39m, in [36mguess_engine[39m[34m(store_spec)[39m
[32m    186[39m [38;5;28;01melse[39;00m:
[32m    187[39m     error_msg = (
[32m    188[39m         [33m"[39m[33mfound the following matches with the input file in xarray[39m[33m'[39m[33ms IO [39m[33m"[39m
[32m    189[39m         [33mf[39m[33m"[39m[33mbackends: [39m[38;5;132;01m{[39;00mcompatible_engines[38;5;132;01m}[39;00m[33m. But their dependencies may not be installed, see:[39m[38;5;130;01m\n[39;00m[33m"[39m
[32m    190[39m         [33m"[39m[33mhttps://docs.xarray.dev/en/stable/user-guide/io.html [39m[38;5;130;01m\n[39;00m[33m"[39m
[32m    191[39m         [33m"[39m[33mhttps://docs.xarray.dev/en/stable/getting-started-guide/installing.html[39m[33m"[39m
[32m    192[39m     )
[32m--> [39m[32m194[39m [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(error_msg)

[31mValueError[39m: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

